language: php
php: 7.4
install: composer install
script:
  - ./vendor/bin/deptrac analyse src/BundleArchitecture/depfile.yml
  - ./vendor/bin/deptrac analyse src/MixedArchitecture/depfile.bundles.yml
  - ./vendor/bin/deptrac analyse src/MixedArchitecture/depfile.in_bundle.yml
  - ./vendor/bin/deptrac analyse src/ProtocolArchitecture/depfile.bundles.yml
  - ./vendor/bin/deptrac analyse src/SymfonyArchitecture/depfile.yml
