name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run deptrac for BundleArchitecture
      run: ./vendor/bin/deptrac analyse src/BundleArchitecture/depfile.yml

    - name: Run deptrac for MixedArchitecture@1
      run: ./vendor/bin/deptrac analyse src/MixedArchitecture/depfile.bundles.yml

    - name: Run deptrac for MixedArchitecture@2
      run: ./vendor/bin/deptrac analyse src/MixedArchitecture/depfile.in_bundle.yml

    - name: Run deptrac for ProtocolArchitecture
      run: ./vendor/bin/deptrac analyse src/ProtocolArchitecture/depfile.bundles.yml

    - name: Run deptrac for SymfonyArchitecture
      run: ./vendor/bin/deptrac analyse src/SymfonyArchitecture/depfile.yml
